# Generated by Django 5.2.11 on 2026-02-12 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ride",
            name="max_participants",
        ),
        migrations.AddField(
            model_name="ride",
            name="gpx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="gpx/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["gpx"]
                    )
                ],
            ),
        ),
    ]
